config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'welcome#index'
end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize user
    user ||= User.new

    can :manage, :all if user.admin?

    cannot :destroy, User, id: user.id
    cannot :lock,    User, id: user.id
    cannot :unlock,  User, id: user.id
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are: :token_authenticatable, :lockable, & :timeoutable
  devise :confirmable,
         :database_authenticatable,
         :lockable,
         :recoverable,
         :registerable,
         :rememberable,
         :trackable,
         :validatable

  devise :omniauthable, omniauth_providers: %i[ facebook github twitter ]

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  scope :admin,           -> { where admin: true }
  scope :access_locked,   -> { where 'locked_at IS NOT NULL AND locked_at >= ?', unlock_in.ago }
  scope :access_unlocked, -> { where 'locked_at IS NULL OR locked_at < ?',       unlock_in.ago }

  attr_accessor :login

  # Devise find for authentication override
  # used to allow authentication via email or username
  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login      = conditions.delete :login
    query      = where conditions

    query = query.where 'lower(username) = :login OR lower(email) = :login', login: login.downcase if login
    query.first
  end

  def self.from_omniauth auth
    info     = auth.info
    email    = info.email
    password = Devise.friendly_token[0, 20]

    user = where(provider: auth.provider, uid: auth.uid).first_or_initialize do |u|
      u.username              = info.nickname.blank? ? email : info.nickname
      u.email                 = email.blank? ? "#{u.username}@users.noreply.meepl.es" : email
      u.password              = password
      u.password_confirmation = password
    end

    user.skip_confirmation!
    user.save
    user
  end

  def self.new_with_session params, session
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email ||= data['email']
      end
    end
  end

  def locked?
    access_locked?
  end

  def unlocked?
    not locked?
  end

  # override for active job
  def send_devise_notification notification, *args
    devise_mailer.send(notification, self, *args).deliver_later
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery

  self.responder = Responder

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, flash: { error: exception.message }
  end

protected

  # Rails 4 permitted parameters for devise only controllers
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :account_update do |user|
      user.permit :email, :password, :password_confirmation, :current_password, :username
    end

    devise_parameter_sanitizer.permit :sign_in do |user|
      user.permit :login, :password, :remember_me
    end

    devise_parameter_sanitizer.permit :sign_up do |user|
      user.permit :email, :password, :password_confirmation, :remember_me, :username
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  before_action :find_user

  Devise.omniauth_providers.each do |provider|
    define_method provider do
      if @user and @user.persisted?
        sign_in_and_redirect_with_flash_for provider
      else
        session["devise.#{ provider }_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
  end

private

  def find_user
    attrs = request.env['omniauth.auth']
    @user = attrs ? User.from_omniauth(attrs) : nil
  end

  def sign_in_and_redirect_with_flash_for provider
    sign_in_and_redirect @user, :event => :authentication # this will throw if @user is not activated
    set_flash_message :notice, :success, kind: provider.to_s.titleize if is_navigational_format?
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title text
    content_for(:title) { "- #{ text }" }
    content_for(:h1)    { text }
  end

end

app/views/application/_footer.html.haml
- if ENV['GAUGES_SITE_ID']
  :javascript
    var _gauges = _gauges || [];
    (function() {
      var t   = document.createElement('script');
      t.type  = 'text/javascript';
      t.async = true;
      t.id    = 'gauges-tracker';
      t.setAttribute('data-site-id', '#{ ENV["GAUGES_SITE_ID"] }');
      t.src = '//secure.gaug.es/track.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(t, s);
    })();

app/views/application/_head.html.haml
%meta{ charset: 'utf-8' }
%meta{ content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible' }
%meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }

= csrf_meta_tag
= javascript_include_tag 'application'
= stylesheet_link_tag    'application'

/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

%title
  = t 'application.name'
  = yield :title

app/views/application/_navbar.html.haml
.navbar.navbar-default.navbar-static-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle{ data: { toggle: 'collapse', target: '.navbar-collapse' }, type: 'button' }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      = link_to t('application.name'), root_path, class: 'navbar-brand'

    .navbar-collapse.collapse

      %ul.nav.navbar-nav.navbar-right
        - if can? :dashboard, :sidekiq
          %li= link_to t('.sidekiq'), sidekiq_web_path

        %li.divider-vertical
          - if user_signed_in?
            %li.dropdown
              = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
                = current_user.username
                %b.caret

              %ul.dropdown-menu
                %li= link_to t('.account'),  edit_user_registration_path
                %li= link_to t('.sign_out'), destroy_user_session_path, :method => :delete

          - else
            %li= link_to t('.sign_up'), new_user_registration_path
            %li= link_to t('.sign_in'), new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html

  %head= render 'head'

  %body{ data: { environment: Rails.env }}
    = render 'navbar'

    .container-fluid
      %header
        - flash.each do |type, message|
          .row
            .col-sm-12
              .flash.alert{ class: "alert-#{ type }" }
                %button.close{ data: { dismiss: 'alert' }, type: 'button' } ×
                = message


      #content= yield
      %footer= render 'footer'

app/views/layouts/devise.html.haml
!!! 5
%html

  %head= render 'head'

  %body{ data: { environment: Rails.env }}
    = render 'navbar'

    .container-fluid
      %header
        .row
          .col-sm-8.col-sm-offset-2
            .page-header
              %h1= yield :h1

      - flash.each do |type, message|
        .row
          .col-sm-8.col-sm-offset-2
            .flash.alert{ class: "alert-#{ type }" }
              %button.close{ data: { dismiss: 'alert' }, type: 'button' } ×
              = message

      = yield
      = render 'devise/shared/links' unless user_signed_in?

app/views/welcome/index.html.haml
- title t '.title'

.row
  .col-sm-12
    .jumbotron
      %h1= t 'application.name'
      %p= t 'application.description'
      %p
        = link_to t('.fork'), 'https://gitlab.devfu.com/devfu/base', class: 'btn btn-danger'
        or
        = link_to 'https://heroku.com/deploy?template=https://gitlab.devfu.com/devfu/base', alt: 'deploy' do
          = image_tag('https://www.herokucdn.com/deploy/button.svg')

- unless user_signed_in?
  .row
    .col-sm-6
      %h2 New Users
      = link_to t('.facebook'), user_facebook_omniauth_authorize_path, class: 'btn btn-block btn-primary'
      = link_to t('.github'),   user_github_omniauth_authorize_path,   class: 'btn btn-block btn-warning'
      = link_to t('.twitter'),  user_twitter_omniauth_authorize_path,  class: 'btn btn-block btn-info'
      = link_to t('.sign_up'),  new_user_registration_path,            class: 'btn btn-block btn-default'

    .col-sm-6
      %h2 Existing users
      = link_to t('.sign_in'), new_user_session_path, class: 'btn btn-block btn-success'